version: '2'
networks:
  wapps:
    external: true
services:
  portainer:
    command: "--logo ${LOGO} --templates ${CATALOGUE}"
    image: "portainer/portainer"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http,https"
      - "traefik.http.routers.portainer.middlewares=wapps-mgmt"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer-https-mgmt.entrypoints=https-mgmt"
      - "traefik.http.routers.portainer-https-mgmt.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer-https-mgmt.tls.certResolver=wapps"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
  traefik:
    command:
    - "--api.insecure=true"
    - "--certificatesResolvers.wapps.acme.dnsChallenge.provider=${DNS_PROVIDER}"
    - "--certificatesResolvers.wapps.acme.email=${EMAIL}"
    - "--certificatesResolvers.wapps.acme.storage=/wapps/acme.json"
    - "--entryPoints.http.address=:80"
    - "--entryPoints.https.address=:443"
    - "--entryPoints.https-mgmt.address=:${HTTPS_MGMT_PORT}"
    - "--providers.docker"
    env_file: ".env"
    image: "traefik"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.wapps-mgmt.redirectregex.permanent=true"
      - "traefik.http.middlewares.wapps-mgmt.redirectregex.regex=^http(s?)://(.*)/(.*)"
      - "traefik.http.middlewares.wapps-mgmt.redirectregex.replacement=https://$${2}:${HTTPS_MGMT_PORT}/$${3}"
      - "traefik.http.middlewares.wapps.redirectscheme.permanent=true"
      - "traefik.http.middlewares.wapps.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.middlewares=wapps-mgmt"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik-https-mgmt.entrypoints=https-mgmt"
      - "traefik.http.routers.traefik-https-mgmt.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik-https-mgmt.tls.certResolver=wapps"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - "wapps"
    ports:
      - "${IP}:80:80"
      - "${IP}:443:443"
      - "${IP}:4443:4443"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_acme:/wapps"
  watchtower:
    command: "--label-enable"
    image: "containrrr/watchtower"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  portainer_data:
  traefik_acme:
